apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hexcall-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hexcall.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hexcall
                port:
                  number: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: hexcall
spec:
  type: ClusterIP
  ports:
    - port: 4000
      name: web
      targetPort: 4000
    - port: 30001 # This is simply a random ephemeral port. Unsure where ex_webrtc configures this
      name: webrtc
      targetPort: 30001
      protocol: UDP
  selector:
    app: hexcall
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hexcall-config
  namespace: default
data:
  PHX_HOST: "hexcall.example"
  PORT: "4000"

  # For minikube, use internal ip of udp-gateway, otherwise this points to a loadbalancer(possibly with dns)
  ICE_URL: "turn:10.99.103.83:3478?transport=udp"

  DATABASE_NAME: "hexcall"
  DATABASE_HOST: "postgres"
  POOL_SIZE: "10"
---
apiVersion: v1
kind: Secret
metadata:
  name: hexcall-secret
  namespace: default
type: Opaque
stringData:
  type: static
  SECRET_KEY_BASE: "8i2C1ef40AaB6IYaXCWuFwjvTaKWDDPEeDehcxoSkgA3AuGyIH6VkU820HNXEywz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexcall-deployment
  labels:
    app: hexcall
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexcall
  template:
    metadata:
      labels:
        app: hexcall
    spec:
      initContainers:
        - name: migrate-db
          image: hexcall
          imagePullPolicy: Never
          command: ["/app/bin/migrate"]
          # args: ["eval", "YourApp.Release.migrate"]
          envFrom:
            - configMapRef:
                name: hexcall-config
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: hexcall-secret
                  key: SECRET_KEY_BASE
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
      containers:
        - name: hexcall
          image: hexcall
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: hexcall-config
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: hexcall-secret
                  key: SECRET_KEY_BASE
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            # Hardcoded user/pass for now. due to namespace partitioning cant read from secret...
            - name: ICE_USERNAME
              value: "user-1"
              # valueFrom:
              # secretKeyRef:
              # name: stunner-auth-secret
              # key: username
            - name: ICE_PASSWORD
              value: "pass-1"
              # valueFrom:
              # secretKeyRef:
              # name: stunner-auth-secret
              # key: password
