apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: libcluster-read-permissions
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-permissions
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: libcluster-read-permissions
  apiGroup: rbac.authorization.k8s.io
